version: "3"
services:
  php:
    container_name: lytican_levtolstoy.php
    volumes:
      - ./app:/var/www/levtolstoy
      - ./app/var/log/php:/var/log/php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    networks:
      - levtolstoy
    ports:
      - 9000:9000
    depends_on:
      - database

  nginx:
    container_name: lytican_levtolstoy.nginx
    image: nginx
    volumes:
      - ./app:/var/www/levtolstoy
      - ./app/var/log/nginx:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - levtolstoy
    ports:
      - ${FORWARD_APP_PORT:-80}:80
    depends_on:
      - php

  database:
    container_name: lytican_levtolstoy.database
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    networks:
      - levtolstoy
    volumes:
      - ./app/var/lib/mysql2:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  levtolstoy:
    driver: bridge
